app:
  correios:
    user: ECT
    password: SRO
    search-type: L
    result-type: T
    language: 101
  mail:
    max-attempts: 1
    max-interval: 30000
    default-sender: rastreador@bomrastreio.com.br
    default-personal: Rastreador BomRastreio
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://docker:3306/bomrastreio?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: a1b2c3d4f9
  mail:
    host: smtp.zoho.com
    username: rastreador@bomrastreio.com.br
    password: $9CJTK!l
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socket-factory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      indent_output: true
keycloak:
  realm: bomrastreio
  bearer-only: true
  auth-server-url: https://conta.bomrastreio.com.br/auth
  ssl-required: external
  resource: bomrastreio-api
  cors: true
  credentials:
    secret: 970deb35-d333-48e2-aea6-22736442b4c2
  securityConstraints:
    - securityCollections:
      - authRoles:
            - api_access
        patterns:
            - /
server:
  port: 8082
